# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/beta-29-cloud-base"
  config.vm.hostname = "workstation"
  config.vm.provider "libvirt" do |v|
      v.memory = '8144'
      v.cpus = 2
      v.storage :file => 'disk1.img', :size => '20G'
      v.storage :file => 'disk2.img', :size => '40G'
  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum udpate || true
    sudo yum install -y python
    sudo pip install ansible || true
  SHELL
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.galaxy_roles_path = "~/work/mine/ansible/roles"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
