# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "libvirt" do |v|
  config.vm.hostname = "devstack"
      v.memory = '8144'
      v.cpus = 2

  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y || true
    sudo yum install -y ansible git vim
  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.galaxy_roles_path = "~/work/mine/ansible/roles"
  end
end
