# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "workstation"
  config.vm.provider "libvirt" do |v|
      v.memory = '24288'
      v.cpus = 2
      v.storage :file, :size => '60G', :type => 'raw', :bus => 'virtio'
      v.nested = true
      v.volume_cache = 'none'
      v.cpu_mode = 'host-passthrough'
  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y python python2-pip || true
    sudo pip install ansible || true
    sudo echo "domain redhat.com" > /etc/resolv.conf
    sudo echo "nameserver 10.11.5.19" >> /etc/resolv.conf
    sudo echo "nameserver 10.5.30.160" >> /etc/resolv.conf
  SHELL
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.galaxy_roles_path = "~/vms/ansible/roles"
      ansible.extra_vars = "~/work/redhat/openstack-testing/environment/base.yaml"
  end
  config.vm.synced_folder "/home/chuck/work", "/vagrant", disabled: true

#  config.vm.provision "file", source: "~/.gitconfig", destination: "$HOME/.gitconfig"
#  config.vm.provision "file", source: "~/.vim", destination: "$HOME/.vim"
#  config.vm.provision "file", source: "~/.vimrc", destination: "$HOME/.vimrc"
#  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "$HOME/.ssh"
#  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "$HOME/.ssh"
end
